In [41]:
import torch

x = torch.randn(3, requires_grad=True)

y = x+2
print(y)
z = y**2*2
print(z)
m = y.mean()
print(m)
# backward function required scalar values or none
n = m.backward()
print(n)
#print(x.grad)

tensor([0.8478, 2.3204, 1.0697], grad_fn=<AddBackward0>)
tensor([ 1.4376, 10.7682,  2.2883], grad_fn=<MulBackward0>)
tensor(1.4126, grad_fn=<MeanBackward0>)
None


In [54]:
x.requires_grad_(False) # stops calculating gradient       

tensor([-1.1522,  0.3204, -0.9303])

In [63]:
weights = torch.ones(4, requires_grad=True)
print(weights)
for epoch in range(3):
    model_output = (weights*3).sum()
    
    # calculate gradient
    model_output.backward()
    
    weights.grad
    
    print(weights.grad)
    
    weights.grad.zero_()

tensor([1., 1., 1., 1.], requires_grad=True)
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [64]:
# psuedocode, doesn't run
# example of using torch stochastic gradient descent
# optimizer and zeroing optimizer after each step
weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor