# Tensors

https://www.youtube.com/watch?v=DbeIqrwb_dE&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4&index=3

In [3]:
import torch
x = torch.empty(2,2)
x

tensor([[1.9014e-34, 4.5572e-41],
        [2.1555e-36, 0.0000e+00]])

In [10]:
x = torch.zeros(2,2, dtype=torch.double)
x

tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)

In [11]:
x.size()

torch.Size([2, 2])

In [13]:
x = torch.tensor([2.5, 0.1])
x

tensor([2.5000, 0.1000])

In [19]:
x = torch.rand(2,3)
y = torch.rand(2,3)
z = x+y
x,y,z

(tensor([[0.3212, 0.7192, 0.0930],
         [0.2261, 0.8196, 0.8757]]),
 tensor([[0.4318, 0.7288, 0.5067],
         [0.4459, 0.3455, 0.7284]]),
 tensor([[0.7530, 1.4481, 0.5997],
         [0.6721, 1.1650, 1.6041]]))

In [21]:
 y.add_(x) # in place

tensor([[1.0743, 2.1673, 0.6927],
        [0.8982, 1.9846, 2.4798]])

In [22]:
y.mul_(x) # in place multiplication

tensor([[0.3451, 1.5588, 0.0644],
        [0.2031, 1.6266, 2.1715]])

In [24]:
x = torch.rand(5,3)
x

tensor([[0.7575, 0.4715, 0.9874],
        [0.7457, 0.4004, 0.9506],
        [0.3421, 0.7489, 0.8525],
        [0.6665, 0.0461, 0.4162],
        [0.4729, 0.8910, 0.6045]])

In [27]:
x[:1] # first row

tensor([[0.7575, 0.4715, 0.9874]])

In [31]:
x[:,0] # first col

tensor([0.7575, 0.7457, 0.3421, 0.6665, 0.4729])

In [34]:
x[0,0] # first el

tensor(0.7575)

In [37]:
x = torch.rand(4,4)
y = x.view(16)
y

tensor([0.9346, 0.7546, 0.8909, 0.9896, 0.1984, 0.9290, 0.8440, 0.6667, 0.6176,
        0.2196, 0.2550, 0.6473, 0.1967, 0.0607, 0.3945, 0.2400])

In [42]:
y = x.view(-1,2) # view will reshape the tensor
y

tensor([[0.9346, 0.7546],
        [0.8909, 0.9896],
        [0.1984, 0.9290],
        [0.8440, 0.6667],
        [0.6176, 0.2196],
        [0.2550, 0.6473],
        [0.1967, 0.0607],
        [0.3945, 0.2400]])

In [45]:
import numpy as np
a = torch.empty(5)
b = a.numpy() # tensor -> numpy array
b

array([1.9013731e-34, 4.5571627e-41, 2.1731579e-36, 0.0000000e+00,
       4.4841551e-44], dtype=float32)

In [46]:
a.add_(1)
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [49]:
a = np.random.randn(4,4)
b = torch.from_numpy(a)
b

tensor([[-0.2454, -0.5995, -0.5989,  0.1792],
        [-0.3703, -0.8119,  0.6914,  0.5839],
        [-1.5819, -0.7963, -0.8371,  0.2983],
        [ 0.2676, -1.4244, -0.2290,  0.7641]], dtype=torch.float64)